# Generated by Django 5.0.7 on 2024-07-11 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='fallback.png', upload_to='images'),
        ),
    ]
